/* Generated by CodeScroll Test Monitor Program Analyzer */

#ifndef CSTM_MONITOR_CONFIG_HEADER_PATH
#include "cstm_monitor_config.h"
#else
#include CSTM_MONITOR_CONFIG_HEADER_PATH
#endif
#ifndef CSTM_TARGET_HEADER_PATH
#include "cstm_target.h"
#else
#include CSTM_TARGET_HEADER_PATH
#endif
#ifndef CSTM_PROBE_HEADER_PATH
#include "cstm_probe.h"
#else
#include CSTM_PROBE_HEADER_PATH
#endif
#ifndef CSTM_TM_PROBE_MACRO_HEADER_PATH
#include "codescroll_TM_probe_macro.h"
#else
#include CSTM_TM_PROBE_MACRO_HEADER_PATH
#endif
#ifndef CSTM_TM_HEADER_HEADER_PATH
#include "codescroll_TM_header.h"

#else
#include CSTM_TM_HEADER_HEADER_PATH
#endif

/* Extern declarations of origin of pointer variables */
#if defined CODESCROLL_MCDC_EVALUATION || defined CODESCROLL_MEM_ENABLE
#define CS_MCDC_347_0(C1, C2, C3, C4, C5, C6, n) \
  (C1 ? (CS_CMM_MCDC_CX(n+0) 1) : \
    (C2 ? (CS_CMM_MCDC_CX(n+1) 1) : \
      (C3 ? (CS_CMM_MCDC_CX(n+2) 1) : \
        (C4 ? (CS_CMM_MCDC_CX(n+3) 1) : \
          (C5 ? (CS_CMM_MCDC_CX(n+4) 1) : \
            (C6 ? (CS_CMM_MCDC_CX(n+5) 1) : (CS_CMM_MCDC_CX(n+6) 0)))))))
#else /* !CODESCROLL_MCDC_EVALUATION && !CODESCROLL_MEM_ENABLE */
#define CS_MCDC_347_0(cs_cmm_C1, cs_cmm_C2, cs_cmm_C3, cs_cmm_C4, cs_cmm_C5, cs_cmm_C6, cs_cmm_n)  CS_MCDC_347_0_ORG
#endif /* CODESCROLL_MCDC_EVALUATION || CODESCROLL_MEM_ENABLE */
#if defined CODESCROLL_MCDC_EVALUATION || defined CODESCROLL_MEM_ENABLE
#define CS_MCDC_347_1(C1, C2, n) \
  (C1 ? \
    (C2 ? (CS_CMM_MCDC_CX(n+0) 1) : (CS_CMM_MCDC_CX(n+1) 0)) : (CS_CMM_MCDC_CX(n+2) 0))
#else /* !CODESCROLL_MCDC_EVALUATION && !CODESCROLL_MEM_ENABLE */
#define CS_MCDC_347_1(cs_cmm_C1, cs_cmm_C2, cs_cmm_n)  CS_MCDC_347_1_ORG
#endif /* CODESCROLL_MCDC_EVALUATION || CODESCROLL_MEM_ENABLE */
#if defined CODESCROLL_MCDC_EVALUATION || defined CODESCROLL_MEM_ENABLE
#define CS_MCDC_347_2(C1, C2, C3, C4, C5, n) \
  (C1 ? (CS_CMM_MCDC_CX(n+0) 1) : \
    (C2 ? (CS_CMM_MCDC_CX(n+1) 1) : \
      (C3 ? (CS_CMM_MCDC_CX(n+2) 1) : \
        (C4 ? (CS_CMM_MCDC_CX(n+3) 1) : \
          (C5 ? (CS_CMM_MCDC_CX(n+4) 1) : (CS_CMM_MCDC_CX(n+5) 0))))))
#else /* !CODESCROLL_MCDC_EVALUATION && !CODESCROLL_MEM_ENABLE */
#define CS_MCDC_347_2(cs_cmm_C1, cs_cmm_C2, cs_cmm_C3, cs_cmm_C4, cs_cmm_C5, cs_cmm_n)  CS_MCDC_347_2_ORG
#endif /* CODESCROLL_MCDC_EVALUATION || CODESCROLL_MEM_ENABLE */
#if defined CODESCROLL_MCDC_EVALUATION || defined CODESCROLL_MEM_ENABLE
#define CS_MCDC_348_0(C1, C2, C3, C4, C5, n) \
  (C1 ? (CS_CMM_MCDC_CX(n+0) 1) : \
    (C2 ? (CS_CMM_MCDC_CX(n+1) 1) : \
      (C3 ? (CS_CMM_MCDC_CX(n+2) 1) : \
        (C4 ? (CS_CMM_MCDC_CX(n+3) 1) : \
          (C5 ? (CS_CMM_MCDC_CX(n+4) 1) : (CS_CMM_MCDC_CX(n+5) 0))))))
#else /* !CODESCROLL_MCDC_EVALUATION && !CODESCROLL_MEM_ENABLE */
#define CS_MCDC_348_0(cs_cmm_C1, cs_cmm_C2, cs_cmm_C3, cs_cmm_C4, cs_cmm_C5, cs_cmm_n)  CS_MCDC_348_0_ORG
#endif /* CODESCROLL_MCDC_EVALUATION || CODESCROLL_MEM_ENABLE */
#if defined CODESCROLL_MCDC_EVALUATION || defined CODESCROLL_MEM_ENABLE
#define CS_MCDC_349_0(C1, C2, n) \
  (C1 ? (CS_CMM_MCDC_CX(n+0) 1) : \
    (C2 ? (CS_CMM_MCDC_CX(n+1) 1) : (CS_CMM_MCDC_CX(n+2) 0)))
#else /* !CODESCROLL_MCDC_EVALUATION && !CODESCROLL_MEM_ENABLE */
#define CS_MCDC_349_0(cs_cmm_C1, cs_cmm_C2, cs_cmm_n)  CS_MCDC_349_0_ORG
#endif /* CODESCROLL_MCDC_EVALUATION || CODESCROLL_MEM_ENABLE */
#if defined CODESCROLL_MCDC_EVALUATION || defined CODESCROLL_MEM_ENABLE
#define CS_MCDC_350_0(C1, C2, n) \
  (C1 ? (CS_CMM_MCDC_CX(n+0) 1) : \
    (C2 ? (CS_CMM_MCDC_CX(n+1) 1) : (CS_CMM_MCDC_CX(n+2) 0)))
#else /* !CODESCROLL_MCDC_EVALUATION && !CODESCROLL_MEM_ENABLE */
#define CS_MCDC_350_0(cs_cmm_C1, cs_cmm_C2, cs_cmm_n)  CS_MCDC_350_0_ORG
#endif /* CODESCROLL_MCDC_EVALUATION || CODESCROLL_MEM_ENABLE */
#if defined CODESCROLL_MCDC_EVALUATION || defined CODESCROLL_MEM_ENABLE
#define CS_MCDC_351_0(C1, C2, n) \
  (C1 ? (CS_CMM_MCDC_CX(n+0) 1) : \
    (C2 ? (CS_CMM_MCDC_CX(n+1) 1) : (CS_CMM_MCDC_CX(n+2) 0)))
#else /* !CODESCROLL_MCDC_EVALUATION && !CODESCROLL_MEM_ENABLE */
#define CS_MCDC_351_0(cs_cmm_C1, cs_cmm_C2, cs_cmm_n)  CS_MCDC_351_0_ORG
#endif /* CODESCROLL_MCDC_EVALUATION || CODESCROLL_MEM_ENABLE */
#if defined CODESCROLL_MCDC_EVALUATION || defined CODESCROLL_MEM_ENABLE
#define CS_MCDC_404_0(C1, C2, n) \
  (C1 ? (CS_CMM_MCDC_CX(n+0) 1) : \
    (C2 ? (CS_CMM_MCDC_CX(n+1) 1) : (CS_CMM_MCDC_CX(n+2) 0)))
#else /* !CODESCROLL_MCDC_EVALUATION && !CODESCROLL_MEM_ENABLE */
#define CS_MCDC_404_0(cs_cmm_C1, cs_cmm_C2, cs_cmm_n)  CS_MCDC_404_0_ORG
#endif /* CODESCROLL_MCDC_EVALUATION || CODESCROLL_MEM_ENABLE */
#if defined CODESCROLL_MCDC_EVALUATION || defined CODESCROLL_MEM_ENABLE
#define CS_MCDC_431_0(C1, C2, n) \
  (C1 ? \
    (C2 ? (CS_CMM_MCDC_CX(n+0) 1) : (CS_CMM_MCDC_CX(n+1) 0)) : (CS_CMM_MCDC_CX(n+2) 0))
#else /* !CODESCROLL_MCDC_EVALUATION && !CODESCROLL_MEM_ENABLE */
#define CS_MCDC_431_0(cs_cmm_C1, cs_cmm_C2, cs_cmm_n)  CS_MCDC_431_0_ORG
#endif /* CODESCROLL_MCDC_EVALUATION || CODESCROLL_MEM_ENABLE */
/* End of extern declarations of origins */

#define CS_MCDC_347_0_ORG	 (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x2C00))) || (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x3400)))|| (TIMx == ((TIM_TypeDef *) (((uint32_t)0x40000000) + 0x0000))) || (TIMx == ((TIM_TypeDef *) (((uint32_t)0x40000000) + 0x0400)))||\
     (TIMx == ((TIM_TypeDef *) (((uint32_t)0x40000000) + 0x0800))) || (TIMx == ((TIM_TypeDef *) (((uint32_t)0x40000000) + 0x0C00)))
#define CS_MCDC_347_1_ORG	 (TIMx != ((TIM_TypeDef *) (((uint32_t)0x40000000) + 0x1000))) && (TIMx != ((TIM_TypeDef *) (((uint32_t)0x40000000) + 0x1400)))
#define CS_MCDC_347_2_ORG	 (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x2C00))) || (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x3400)))|| (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x4000)))|| (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x4400))) || (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x4800)))
#define CS_MCDC_348_0_ORG	 (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x2C00))) || (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x3400)))|| (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x4000)))||\
     (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x4400)))|| (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x4800)))
#define CS_MCDC_349_0_ORG	 (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x2C00))) || (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x3400)))
#define CS_MCDC_350_0_ORG	 (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x2C00))) || (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x3400)))
#define CS_MCDC_351_0_ORG	 (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x2C00))) || (TIMx == ((TIM_TypeDef *) ((((uint32_t)0x40000000) + 0x10000) + 0x3400)))
#define CS_MCDC_404_0_ORG	 (TIM_Channel == ((uint16_t)0x0000)) ||(TIM_Channel == ((uint16_t)0x0008))
#define CS_MCDC_431_0_ORG	 (itstatus != (uint16_t)RESET) && (itenable != (uint16_t)RESET)
