/* Generated by CodeScroll Test Monitor Program Analyzer */

#ifndef CSTM_MONITOR_CONFIG_HEADER_PATH
#include "cstm_monitor_config.h"
#else
#include CSTM_MONITOR_CONFIG_HEADER_PATH
#endif
#ifndef CSTM_TARGET_HEADER_PATH
#include "cstm_target.h"
#else
#include CSTM_TARGET_HEADER_PATH
#endif
#ifndef CSTM_PROBE_HEADER_PATH
#include "cstm_probe.h"
#else
#include CSTM_PROBE_HEADER_PATH
#endif
#ifndef CSTM_TM_PROBE_MACRO_HEADER_PATH
#include "codescroll_TM_probe_macro.h"
#else
#include CSTM_TM_PROBE_MACRO_HEADER_PATH
#endif
#ifndef CSTM_TM_HEADER_HEADER_PATH
#include "codescroll_TM_header.h"

#else
#include CSTM_TM_HEADER_HEADER_PATH
#endif

/* Extern declarations of origin of pointer variables */
#if defined CODESCROLL_MCDC_EVALUATION || defined CODESCROLL_MEM_ENABLE
#define CS_MCDC_140_2(C1, C2, n) \
  (C1 ? \
    (C2 ? (CS_CMM_MCDC_CX(n+0) 1) : (CS_CMM_MCDC_CX(n+1) 0)) : (CS_CMM_MCDC_CX(n+2) 0))
#else /* !CODESCROLL_MCDC_EVALUATION && !CODESCROLL_MEM_ENABLE */
#define CS_MCDC_140_2(cs_cmm_C1, cs_cmm_C2, cs_cmm_n)  CS_MCDC_140_2_ORG
#endif /* CODESCROLL_MCDC_EVALUATION || CODESCROLL_MEM_ENABLE */
#if defined CODESCROLL_MCDC_EVALUATION || defined CODESCROLL_MEM_ENABLE
#define CS_MCDC_140_3(C1, C2, n) \
  (C1 ? \
    (C2 ? (CS_CMM_MCDC_CX(n+0) 1) : (CS_CMM_MCDC_CX(n+1) 0)) : (CS_CMM_MCDC_CX(n+2) 0))
#else /* !CODESCROLL_MCDC_EVALUATION && !CODESCROLL_MEM_ENABLE */
#define CS_MCDC_140_3(cs_cmm_C1, cs_cmm_C2, cs_cmm_n)  CS_MCDC_140_3_ORG
#endif /* CODESCROLL_MCDC_EVALUATION || CODESCROLL_MEM_ENABLE */
#if defined CODESCROLL_MCDC_EVALUATION || defined CODESCROLL_MEM_ENABLE
#define CS_MCDC_140_4(C1, C2, n) \
  (C1 ? \
    (C2 ? (CS_CMM_MCDC_CX(n+0) 1) : (CS_CMM_MCDC_CX(n+1) 0)) : (CS_CMM_MCDC_CX(n+2) 0))
#else /* !CODESCROLL_MCDC_EVALUATION && !CODESCROLL_MEM_ENABLE */
#define CS_MCDC_140_4(cs_cmm_C1, cs_cmm_C2, cs_cmm_n)  CS_MCDC_140_4_ORG
#endif /* CODESCROLL_MCDC_EVALUATION || CODESCROLL_MEM_ENABLE */
#if defined CODESCROLL_MCDC_EVALUATION || defined CODESCROLL_MEM_ENABLE
#define CS_MCDC_152_0(C1, C2, n) \
  (C1 ? \
    (C2 ? (CS_CMM_MCDC_CX(n+0) 1) : (CS_CMM_MCDC_CX(n+1) 0)) : (CS_CMM_MCDC_CX(n+2) 0))
#else /* !CODESCROLL_MCDC_EVALUATION && !CODESCROLL_MEM_ENABLE */
#define CS_MCDC_152_0(cs_cmm_C1, cs_cmm_C2, cs_cmm_n)  CS_MCDC_152_0_ORG
#endif /* CODESCROLL_MCDC_EVALUATION || CODESCROLL_MEM_ENABLE */
#if defined CODESCROLL_MCDC_EVALUATION || defined CODESCROLL_MEM_ENABLE
#define CS_MCDC_153_0(C1, C2, n) \
  (C1 ? \
    (C2 ? (CS_CMM_MCDC_CX(n+0) 1) : (CS_CMM_MCDC_CX(n+1) 0)) : (CS_CMM_MCDC_CX(n+2) 0))
#else /* !CODESCROLL_MCDC_EVALUATION && !CODESCROLL_MEM_ENABLE */
#define CS_MCDC_153_0(cs_cmm_C1, cs_cmm_C2, cs_cmm_n)  CS_MCDC_153_0_ORG
#endif /* CODESCROLL_MCDC_EVALUATION || CODESCROLL_MEM_ENABLE */
/* End of extern declarations of origins */

#define CS_MCDC_140_2_ORG	 (status == FLASH_COMPLETE) && (WRP1_Data != 0xFF)
#define CS_MCDC_140_3_ORG	 (status == FLASH_COMPLETE) && (WRP2_Data != 0xFF)
#define CS_MCDC_140_4_ORG	 (status == FLASH_COMPLETE)&& (WRP3_Data != 0xFF)
#define CS_MCDC_152_0_ORG	 (status == FLASH_BUSY) && (Timeout != 0x00)
#define CS_MCDC_153_0_ORG	 (status == ((uint32_t)0x00000001)) && (Timeout != 0x00)
